const { JsonWebTokenError } = require('jsonwebtoken')

const roles = ['Frontend', 'Backend', 'Graphic Designer', 'UX/UI', 'Devops', 'Project Manager'];
const categories = ['Website', 'Mobile App', 'Ecommerce', 'SAAS'];
const hiring_options = ['Shares', 'Flat Rate'];
const devUsers = [
  {
    username: 'jeb',
    email: 'jeb352@gmail.com',
    firstname: 'Jeb',
    lastname: 'Eichs',
    rating: 4,
    user_type_id: 1,
    rating: 4,
    bio: 'Ready to dedicate time to moving this idea forward.',
    visionary_categories: [categories[0], categories[2], categories[3]],
    profile_image: 'profile19.jpg',
    connections: [1,7,12],
    token_version: 0,
    notifications: [{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}],
    tasks: [{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}],
    notification_settings: { messages: true, added_connection: true, project_invitation: true },
    subscription_settings: { featured_projects: true, weekly_news: true, updates: true },
    dev_roles: ["Frontend","Graphic Designer"],
    dev_categories: ["Website","Mobile App","Ecommerce","SAAS"],
    dev_skills: ["JavaScript","VueJs","Photoshop"],
    hiring_options: ["Shares","Flat Rate"],
    dev_bio: 'Frontend and Backend developer with 5 years of experience building webapps and saas projects.',
    dev_rating: 4
  },
  {
    username: 'jen38950',
    email: 'jen@gmail.com',
    firstname: 'Jen',
    lastname: 'Smith',
    rating: 3,
    user_type_id: 1,
    rating: 3,
    bio: 'Ready to dedicate time to moving this idea forward.',
    visionary_categories: [...categories],
    profile_image: 'profile15.jpg',
    connections: [2,8,13],
    token_version: 0,
    notifications: [{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}],
    tasks: [{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}],
    notification_settings: { messages: true, added_connection: true, project_invitation: true },
    subscription_settings: { featured_projects: true, weekly_news: true, updates: true },
    dev_roles: ["Graphic Designer"],
    dev_categories: ["Website","Ecommerce","SAAS"],
    dev_skills: ["Photoshop","Zeplin"],
    hiring_options: ["Shares"],
    dev_bio: 'Graphic designer with master photoshop and illustrator skills. Can create graphics for any type of project.',
    dev_rating: 5
  },
  {
    username: 'beny89',
    email: 'beny89@gmail.com',
    firstname: 'Ben',
    lastname: 'Antoitte',
    rating: 5,
    user_type_id: 1,
    rating: 5,
    bio: 'Ready to dedicate time to moving this idea forward.',
    visionary_categories: [...categories],
    profile_image: 'profile14.jpg',
    connections: [4,9,14],
    token_version: 0,
    notifications: [{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}],
    tasks: [{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}],
    notification_settings: { messages: true, added_connection: true, project_invitation: true },
    subscription_settings: { featured_projects: true, weekly_news: true, updates: true },
    dev_roles: ["Graphic Designer","UX/UI"],
    dev_categories: ["Ecommerce","SAAS"],
    dev_skills: ["Photoshop","Zeplin"],
    hiring_options: ["Flat Rate"],
    dev_bio: 'Capable of taking on any graphic role. UX/UI and graphic designer.',
    dev_rating: 4
  },
  {
    username: 'appmaker',
    email: 'appmaker@gmail.com',
    firstname: 'Ben',
    lastname: 'Hill',
    rating: 5,
    user_type_id: 1,
    rating: 5,
    bio: 'Ready to dedicate time to moving this idea forward.',
    visionary_categories: [...categories],
    profile_image: 'profile13.jpg',
    connections: null,
    token_version: 0,
    notifications: [{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}],
    tasks: [{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}],
    notification_settings: { messages: true, added_connection: true, project_invitation: true },
    subscription_settings: { featured_projects: true, weekly_news: true, updates: true },
    dev_roles: ["Devops"],
    dev_categories: ["Website","Mobile App"],
    dev_skills: ["Android Developement"],
    hiring_options: ["Flat Rate"],
    dev_bio: 'Skilled devops engineer. Experience with CI/CD like jenkins and gitlab. Setting up production environments and pipelines.',
    dev_rating: 5
  },
  {
    username: 'waveybits',
    email: 'waveybits@gmail.com',
    firstname: 'Wavey',
    lastname: 'Boseman',
    rating: 4,
    user_type_id: 1,
    rating: 4,
    bio: 'Ready to dedicate time to moving this idea forward.',
    visionary_categories: [categories[1]],
    profile_image: 'profile12.jpg',
    connections: [3,4,9,10,11,12,13,14,15],
    token_version: 0,
    notifications: [{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}],
    tasks: [{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}],
    notification_settings: { messages: true, added_connection: true, project_invitation: true },
    subscription_settings: { featured_projects: true, weekly_news: true, updates: true },
    dev_roles: ["Project Manager"],
    dev_categories: ["Website","Mobile App","Ecommerce","SAAS"],
    dev_skills: ["JavaScript","React","VueJs"],
    hiring_options: ["Shares"],
    dev_bio: 'Ready to dedicate time to moving this idea forward.',
    dev_rating: 3
  },
  {
    username: 'bossman',
    email: 'boss@devally.com',
    firstname: 'Boss',
    lastname: 'Man',
    rating: 5,
    user_type_id: 1,
    rating: 5,
    bio: 'Ready to dedicate time to moving this idea forward.',
    visionary_categories: [categories[0], categories[1], categories[2]],
    profile_image: 'profile6.jpg',
    connections: [7,11,4],
    token_version: 0,
    notifications: [{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}],
    tasks: [{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}],
    notification_settings: { messages: true, added_connection: true, project_invitation: true },
    subscription_settings: { featured_projects: true, weekly_news: true, updates: true },
    dev_roles: ["Backend"],
    dev_categories: ["Website","Mobile App","Ecommerce","SAAS"],
    dev_skills: ["JavaScript"],
    hiring_options: ["Shares","Flat Rate"],
    dev_bio: 'Junior backend developer. Proficient in C# as well as Java with Spring Boot. 3 years developing backend API\'s and services',
    dev_rating: 2
  },
  {
    username: 'cinyloo',
    email: 'cindyloo@gmail.com',
    firstname: 'Cindy',
    lastname: 'Loo',
    rating: 5,
    user_type_id: 1,
    rating: 5,
    bio: 'Ready to dedicate time to moving this idea forward.',
    visionary_categories: [...categories],
    profile_image: 'profile10.jpg',
    connections: null,
    token_version: 0,
    notifications: [{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}],
    tasks: [{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}],
    notification_settings: { messages: true, added_connection: true, project_invitation: true },
    subscription_settings: { featured_projects: true, weekly_news: true, updates: true },
    dev_roles: ["Frontend"],
    dev_categories: ["Mobile App","SAAS"],
    dev_skills: ["JavaScript","React","VueJs"],
    hiring_options: ["Flat Rate"],
    dev_bio: 'Can build any web application using ReactJs, Bootstrap and other 3rd party services. Have experience designing authoriztion logic and managing large number of users',
    dev_rating: 5
  },
  {
    username: 'androidDev',
    email: 'androiddev@gmail.com',
    firstname: 'Clint',
    lastname: 'Summer',
    rating: 4,
    user_type_id: 1,
    rating: 4,
    bio: 'Work retail and have always wanted to create a mobile app. Looking for experienced team members.',
    visionary_categories: [...categories],
    profile_image: 'profile9.jpg',
    connections: null,
    token_version: 0,
    notifications: [{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}],
    tasks: [{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}],
    notification_settings: { messages: true, added_connection: true, project_invitation: true },
    subscription_settings: { featured_projects: true, weekly_news: false, updates: true },
    dev_roles: ["Frontend"],
    dev_categories: ["Website","Ecommerce","SAAS"],
    dev_skills: ["JavaScript","VueJs"],
    hiring_options: ["Shares","Flat Rate"],
    dev_bio: 'Have been building websites for 10 years. Familiar with all frontend frameworks inclucing React, Angular and VueJS.',
    dev_rating: 4
  },
  {
    username: 'yoohoo',
    email: 'yoohoo@gmail.com',
    firstname: 'Yoo',
    lastname: 'Hoo',
    user_type_id: 1,
    rating: null,
    bio: 'Work retail and have always wanted to create a mobile app. Looking for experienced team members.',
    visionary_categories: [categories[2]],
    profile_image: 'profile8.jpg',
    connections: null,
    token_version: 0,
    notifications: [{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}],
    tasks: [{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}],
    notification_settings: { messages: true, added_connection: true, project_invitation: true },
    subscription_settings: { featured_projects: true, weekly_news: false, updates: true },
    dev_roles: ["Project Manager"],
    dev_categories: ["Website","Ecommerce","SAAS"],
    dev_skills: ["JavaScript"],
    hiring_options: ["Shares"],
    dev_bio: '8 years of project managment experience. Use Agile SDLC methodoligies. Can organize your team and get the best output out of the team.',
    dev_rating: 3
  },
  {
    username: 'gamer3521',
    email: 'gamer3521@gmail.com',
    firstname: 'Jeff',
    lastname: 'Bloom',
    rating: 3,
    user_type_id: 1,
    rating: 3,
    bio: 'Work retail and have always wanted to create a mobile app. Looking for experienced team members.',
    visionary_categories: [categories[0]],
    profile_image: 'profile7.jpg',
    connections: null,
    token_version: 0,
    notifications: [{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}],
    tasks: [{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}],
    notification_settings: { messages: true, added_connection: true, project_invitation: true },
    subscription_settings: { featured_projects: true, weekly_news: false, updates: true },
    dev_roles: ["Graphic Designer","UX/UI"],
    dev_categories: ["Mobile App","Ecommerce","SAAS"],
    dev_skills: ["Photoshop","Zeplin"],
    hiring_options: ["Shares"],
    dev_bio: 'Capable of taking on any graphic role. UX/UI and graphic designer.',
    dev_rating: 4
  },
  {
    username: 'iosDev',
    email: 'iosDev@gmail.com',
    firstname: 'Anderson',
    lastname: 'Silva',
    user_type_id: 1,
    rating: null,
    bio: 'Work retail and have always wanted to create a mobile app. Looking for experienced team members.',
    visionary_categories: [categories[0], categories[1], categories[2]],
    profile_image: 'profile3.jpg',
    connections: null,
    token_version: 0,
    notifications: [{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}],
    tasks: [{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}],
    notification_settings: { messages: true, added_connection: true, project_invitation: true },
    subscription_settings: { featured_projects: true, weekly_news: false, updates: true },
    dev_roles: ["Frontend"],
    dev_categories: ["Mobile App","Ecommerce"],
    dev_skills: ["JavaScript","React","VueJs"],
    hiring_options: ["Shares"],
    dev_bio:'Frontend and Backend developer with 5 years of experience building webapps and saas projects.',
    dev_rating: 3
  },
  {
    username: 'JoshB',
    email: 'JoshB@gmail.com',
    firstname: 'Josh',
    lastname: 'Baker',
    rating: 4,
    user_type_id: 1,
    rating: 4,
    bio: 'Work retail and have always wanted to create a mobile app. Looking for experienced team members.',
    visionary_categories: [...categories],
    profile_image: 'profile2.jpg',
    connections: null,
    token_version: 0,
    notifications: [{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}],
    tasks: [{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}],
    notification_settings: { messages: true, added_connection: true, project_invitation: true },
    subscription_settings: { featured_projects: true, weekly_news: false, updates: true },
    dev_roles: ["Devops"],
    dev_categories: ["Ecommerce","SAAS"],
    dev_skills: ["JavaScript","Python"],
    hiring_options: ["Shares"],
    dev_bio: 'Master of Devops',
    dev_rating: 5
  },
  {
    username: 'Gamebread',
    email: 'Gamebread@gmail.com',
    firstname: 'Jorge',
    lastname: 'Masvidal',
    user_type_id: 1,
    rating: null,
    bio: 'Not sure what to put here. Looking forward to starting my project.',
    visionary_categories: [...categories],
    profile_image: 'profile4.jpg',
    connections: null,
    token_version: 0,
    notifications: [{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}],
    tasks: [{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}],
    notification_settings: { messages: true, added_connection: true, project_invitation: true },
    subscription_settings: { featured_projects: true, weekly_news: false, updates: true },
    dev_roles: ["Devops"],
    dev_categories: ["SAAS"],
    dev_skills: ["JavaScript","Python"],
    hiring_options: ["Shares"],
    dev_bio: 'Looking for someone to setup your pipelines and get your project setup for production. I\'m your guy!',
    dev_rating: 2
  },
  {
    username: 'bullet',
    email: 'bullet@gmail.com',
    firstname: 'Valentina',
    lastname: 'Shevchenko',
    user_type_id: 1,
    rating: null,
    bio: 'Not sure what to put here. Looking forward to starting my project.',
    visionary_categories: [...categories],
    profile_image: 'profile11.jpg',
    connections: null,
    token_version: 0,
    notifications: [{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}],
    tasks: [{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}],
    notification_settings: { messages: true, added_connection: true, project_invitation: true },
    subscription_settings: { featured_projects: true, weekly_news: false, updates: true },
    dev_roles: ["Project Manager"],
    dev_categories: ["Mobile App","SAAS"],
    dev_skills: ["JavaScript","React","Photoshop"],
    hiring_options: ["Shares"],
    dev_bio: 'Project manager. Have worked for startups before and am familiar with the fast pace of a startup.',
    dev_rating: 5
  },
  {
    username: 'The_Lioness',
    email: 'thelioness@gmail.com',
    firstname: 'Amanda',
    lastname: 'Nunes',
    user_type_id: 1,
    rating: null,
    bio: 'Not sure what to put here. Looking forward to starting my project.',
    visionary_categories: [categories[1], categories[2]],
    profile_image: 'profile5.jpg',
    connections: null,
    token_version: 0,
    notifications: [{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}],
    tasks: [{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}],
    notification_settings: { messages: true, added_connection: true, project_invitation: true },
    subscription_settings: { featured_projects: true, weekly_news: false, updates: true },
    dev_roles: ["Frontend"],
    dev_categories: ["Mobile App","Ecommerce","SAAS"],
    dev_skills: ["JavaScript","VueJs"],
    hiring_options: ["Shares"],
    dev_bio: 'Years of experience building ecommerce sites. Woocommerce, custom builds. DM me.',
    dev_rating: 1
  }
]



const userId5 = {
    id: 5,
    username: "waveybits",
    email: "waveybits@gmail.com",
    firstname: "Wavey",
    lastname: "Boseman",
    bio: "Ready to dedicate time to moving this idea forward.",
    visionary_categories: ["Mobile App"],
    rating: 4,
    profile_image: "profile12.jpg",
    user_type_id: "1",
    connections: [3,4,9,10,11,12,13,14,15],
    notifications: [
        {
            "senderId": 4,
            "projectId": null,
            "message": "Added you as a connection"
        },
        {
            "senderId": 12,
            "projectId": 4,
            "message": "Recieved a project invitation"
        }
    ],
    tasks: [
        {
            "projectId": 3,
            "message": "Find a front-end developer that has experience with VueJS"
        },
        {
            "projectId": 11,
            "message": "Create designs. Jen should have them completed by noon today"
        },
        {
            "projectId": 21,
            "message": "Determine where to host application. Azure, Google Cloud and AWS are some viable options."
        }
    ],
    notification_settings: { "messages": true,"added_connection": true,"project_invitation": true },
    subscription_settings: { "featured_projects": true,"weekly_news": true,"updates": true },
    token_version: 0,
    dev_roles: ["Project Manager"],
    dev_categories: ["Website","Mobile App","Ecommerce","SAAS"],
    dev_skills: ["JavaScript","React","VueJs" ],
    hiring_options: ["Shares"],
    dev_bio: "8 years of project managment experience. Use Agile SDLC methodoligies. Can organize your team and get the best output out of the team.",
    dev_rating: 3
}


module.exports = {
  devUsers,
  userId5
}
