module.exports = [
  {
    username: 'jeb',
    password: 'password',
    firstname: 'Jeb',
    lastname: 'Eichs',
    account_types: JSON.stringify(['entrepreneur','developer']),
    skills: JSON.stringify(['SPAs', 'Frontend', 'Websites', 'Graphic Design']),
    hiring_options: JSON.stringify(['Shares']),
    rating: 5,
    profile_image: 'profile3.jpg'
  },
  {
    username: 'jen38950',
    password: 'password',
    firstname: 'Jen',
    lastname: 'Smith',
    account_types: JSON.stringify(['developer']),
    skills: JSON.stringify(['SPAs', 'Backend', 'Websites', 'Graphic Design']),
    hiring_options: JSON.stringify(['Flat Rate','Shares']),
    rating: 3,
    profile_image: 'profile5.jpg'
  },
  {
    username: 'beny89',
    password: 'password',
    firstname: 'Ben',
    lastname: 'Antoitte',
    account_types: JSON.stringify(['developer']),
    skills: JSON.stringify(['Java', 'Spring Boot', 'Backend']),
    hiring_options: JSON.stringify(['Flat Rate','Shares']),
    rating: 4,
    profile_image: 'profile2.jpg'
  },
  {
    username: 'appmaker',
    password: 'password',
    firstname: 'Ben',
    lastname: 'Hill',
    account_types: JSON.stringify(['developer']),
    skills: JSON.stringify(['UX/UI', 'Graphic Design']),
    hiring_options: JSON.stringify(['Flat Rate','Shares']),
    rating: 4,
    profile_image: 'profile4.jpg'
  },
  {
    username: 'cindyloo',
    password: 'password',
    firstname: 'Cindy',
    lastname: 'Summer',
    account_types: JSON.stringify(['developer']),
    skills: JSON.stringify(['UX/UI', 'Graphic Design']),
    hiring_options: JSON.stringify(['Flat Rate','Shares']),
    rating: 1,
    profile_image: 'user_profile.jpg'
  },
  {
    username: 'androidDev',
    password: 'password',
    firstname: 'Cindy',
    lastname: 'Summer',
    account_types: JSON.stringify(['developer']),
    skills: JSON.stringify(['UX/UI', 'Graphic Design']),
    hiring_options: JSON.stringify(['Flat Rate']),
    rating: 5,
    profile_image: 'profile6.jpg'
  },
  {
    username: 'ios-dev',
    password: 'password',
    firstname: 'Cindy',
    lastname: 'Summer',
    account_types: JSON.stringify(['developer']),
    skills: JSON.stringify(['UX/UI', 'Graphic Design']),
    hiring_options: JSON.stringify(['Shares']),
    rating: 5,
    profile_image: 'profile7.jpg'
  },
  {
    username: 'bestapps',
    password: 'password',
    firstname: 'Cindy',
    lastname: 'Summer',
    account_types: JSON.stringify(['developer']),
    skills: JSON.stringify(['UX/UI', 'Graphic Design']),
    hiring_options: JSON.stringify(['Flat Rate','Shares']),
    rating: 4,
    profile_image: 'profile8.jpg'
  },
  {
    username: 'game-maker',
    password: 'password',
    firstname: 'Cindy',
    lastname: 'Summer',
    account_types: JSON.stringify(['developer']),
    skills: JSON.stringify(['UX/UI', 'Graphic Design']),
    hiring_options: JSON.stringify(['Flat Rate','Shares']),
    rating: 4,
    profile_image: 'profile9.jpg'
  },
  {
    username: 'yoohoo',
    password: 'password',
    firstname: 'Cindy',
    lastname: 'Summer',
    account_types: JSON.stringify(['developer']),
    skills: JSON.stringify(['Devops']),
    hiring_options: JSON.stringify(['Flat Rate','Shares']),
    rating: 4,
    profile_image: 'profile10.jpg'
  },
  {
    username: 'googleplaydev',
    password: 'password',
    firstname: 'Cindy',
    lastname: 'Summer',
    account_types: JSON.stringify(['developer']),
    skills: JSON.stringify(['UX/UI', 'Graphic Design']),
    hiring_options: JSON.stringify(['Hourly','Shares']),
    rating: 2,
    profile_image: 'profile11.jpg'
  },
  {
    username: 'gamer3521',
    password: 'password',
    firstname: 'Cindy',
    lastname: 'Summer',
    account_types: JSON.stringify(['developer']),
    skills: JSON.stringify(['UX/UI', 'Graphic Design']),
    hiring_options: JSON.stringify(['Hourly','Shares']),
    rating: 1,
    profile_image: 'profile12.jpg'
  },
  {
    username: 'user1',
    password: 'password',
    firstname: 'Cindy',
    lastname: 'Summer',
    account_types: JSON.stringify(['developer']),
    skills: JSON.stringify(['UX/UI', 'Graphic Design']),
    hiring_options: JSON.stringify(['Hourly','Shares']),
    rating: 4,
    profile_image: 'profile13.jpg'
  },
  {
    username: 'jeffvan',
    password: 'password',
    firstname: 'Cindy',
    lastname: 'Summer',
    account_types: JSON.stringify(['developer']),
    skills: JSON.stringify(['UX/UI', 'Graphic Design']),
    hiring_options: JSON.stringify(['Hourly','Shares']),
    rating: 5,
    profile_image: 'profile14.jpg'
  },
  {
    username: 'joshb',
    password: 'password',
    firstname: 'Cindy',
    lastname: 'Summer',
    account_types: JSON.stringify(['developer']),
    skills: JSON.stringify(['UX/UI', 'Graphic Design']),
    hiring_options: JSON.stringify(['Hourly','Shares']),
    rating: 4,
    profile_image: 'profile15.jpg'
  },
  {
    username: 'waveygravy',
    password: 'password',
    firstname: 'Cindy',
    lastname: 'Summer',
    account_types: JSON.stringify(['developer']),
    skills: JSON.stringify(['UX/UI', 'Graphic Design']),
    hiring_options: JSON.stringify(['Hourly','Shares']),
    rating: 4,
    profile_image: 'profile16.jpg'
  },
  {
    username: 'bitcoinman',
    password: 'password',
    firstname: 'Cindy',
    lastname: 'Summer',
    account_types: JSON.stringify(['developer']),
    skills: JSON.stringify(['Frontend', 'Backend']),
    hiring_options: JSON.stringify(['Hourly','Shares']),
    rating: 3,
    profile_image: 'profile17.jpg'
  },
  {
    username: 'webull',
    password: 'password',
    firstname: 'Cindy',
    lastname: 'Summer',
    account_types: JSON.stringify(['developer']),
    skills: JSON.stringify(['UX/UI', 'Graphic Design']),
    hiring_options: JSON.stringify(['Hourly','Shares']),
    rating: 4,
    profile_image: 'profile18.jpg'
  },
  {
    username: 'scoobydoo',
    password: 'password',
    firstname: 'Cindy',
    lastname: 'Summer',
    account_types: JSON.stringify(['developer']),
    skills: JSON.stringify(['UX/UI', 'Graphic Design']),
    hiring_options: JSON.stringify(['Hourly','Shares']),
    rating: 2,
    profile_image: 'profile19.jpg'
  },
]
