// (c) Waveybits Inc. <2021>
// ALL RIGHTS RESERVED

const bcrypt = require('bcrypt');
const password = 'password';
const hash = bcrypt.hashSync(password, 10);

module.exports = [
  {
    username: 'jeb',
    email: 'jeb352@gmail.com',
    password: hash,
    firstname: 'Jeb',
    lastname: 'Eichs',
    rating: 4,
    user_type_id: 3,
    profile_image: 'profile19.jpg'
  },
  {
    username: 'jen38950',
    email: 'jen@gmail.com',
    password: hash,
    firstname: 'Jen',
    lastname: 'Smith',
    rating: 3,
    user_type_id: 1,
    profile_image: 'profile15.jpg'
  },
  {
    username: 'beny89',
    email: 'beny89@gmail.com',
    password: hash,
    firstname: 'Ben',
    lastname: 'Antoitte',
    rating: 5,
    user_type_id: 3,
    profile_image: 'profile14.jpg'
  },
  {
    username: 'appmaker',
    email: 'appmaker@gmail.com',
    password: hash,
    firstname: 'Ben',
    lastname: 'Hill',
    user_type_id: 1,
    profile_image: 'profil13.jpg'
  },
  {
    username: 'waveybits',
    email: 'waveybits@gmail.com',
    password: hash,
    firstname: 'Wavey',
    lastname: 'Boseman',
    rating: 4,
    user_type_id: 3,
    profile_image: 'profile12.jpg'
  },
  {
    username: 'bossman',
    email: 'boss@devally.com',
    password: hash,
    firstname: 'Boss',
    lastname: 'Man',
    rating: 5,
    user_type_id: 3,
    profile_image: 'profile6.jpg'
  },
  {
    username: 'cinyloo',
    email: 'cindyloo@gmail.com',
    password: hash,
    firstname: 'Cindy',
    lastname: 'Loo',
    rating: 5,
    user_type_id: 1,
    profile_image: 'profile10.jpg'
  },
  {
    username: 'androidDev',
    email: 'androiddev@gmail.com',
    password: hash,
    firstname: 'Clint',
    lastname: 'Summer',
    rating: 4,
    user_type_id: 1,
    profile_image: 'profile9.jpg'
  },
  {
    username: 'yoohoo',
    email: 'yoohoo@gmail.com',
    password: hash,
    firstname: 'Yoo',
    lastname: 'Hoo',
    user_type_id: 1,
    profile_image: 'profile8.jpg'
  },
  {
    username: 'gamer3521',
    email: 'gamer3521@gmail.com',
    password: hash,
    firstname: 'Jeff',
    lastname: 'Bloom',
    rating: 3,
    user_type_id: 1,
    profile_image: 'profile7.jpg'
  },
  {
    username: 'iosDev',
    email: 'iosDev@gmail.com',
    password: hash,
    firstname: 'Anderson',
    lastname: 'Silva',
    user_type_id: 1,
    profile_image: 'profile3.jpg'
  },
  {
    username: 'JoshB',
    email: 'JoshB@gmail.com',
    password: hash,
    firstname: 'Josh',
    lastname: 'Baker',
    rating: 4,
    user_type_id: 1,
    profile_image: 'profile2.jpg',
  },
  {
    username: 'Gamebread',
    email: 'Gamebread@gmail.com',
    password: hash,
    firstname: 'Jorge',
    lastname: 'Masvidal',
    user_type_id: 1,
    profile_image: 'profile4.jpg',
  },
  {
    username: 'bullet',
    email: 'bullet@gmail.com',
    password: hash,
    firstname: 'Valentina',
    lastname: 'Shevchenko',
    user_type_id: 1,
    profile_image: 'profile11.jpg',

  },
  {
    username: 'The_Lioness',
    email: 'thelioness@gmail.com',
    password: hash,
    firstname: 'Amanda',
    lastname: 'Nunes',
    user_type_id: 1,
    profile_image: 'profile5.jpg',
  },
  {
    username: 'Vision',
    email: 'vision@gmail.com',
    password: hash,
    firstname: 'Vision',
    lastname: 'Marvel',
    user_type_id: 2,
    profile_image: 'profile2.jpg',
  },
  {
    username: 'WandaM',
    email: 'wandam@gmail.com',
    password: hash,
    firstname: 'Wanda',
    lastname: 'Rhomboso',
    user_type_id: 2,
    profile_image: 'profile8.jpg',
  },
  {
    username: 'IronMan',
    email: 'ironman@gmail.com',
    password: hash,
    firstname: 'Tony',
    lastname: 'Stark',
    user_type_id: 2,
    profile_image: 'profile10.jpg',
  },
  {
    username: 'Captain America',
    email: 'captainamerica@gmail.com',
    password: hash,
    firstname: 'Cap',
    lastname: 'Rogers',
    user_type_id: 2,
    profile_image: 'profile10.jpg',
  },
  {
    username: 'HulkDev',
    email: 'hulkdev@gmail.com',
    password: hash,
    firstname: 'Bruce',
    lastname: 'Banner',
    user_type_id: 2,
    profile_image: 'profile12.jpg',
  },
  {
    username: 'BlackWidow',
    email: 'blackwidow@gmail.com',
    password: hash,
    firstname: 'Natasha',
    lastname: 'Romanov',
    user_type_id: 2,
    profile_image: 'profile3.jpg',
  },
  {
    username: 'Thor',
    email: 'thor@gmail.com',
    password: hash,
    firstname: 'Thor',
    lastname: 'Romanov',
    user_type_id: 2,
    profile_image: 'profile12.jpg',
  },
  {
    username: 'Rhonda32',
    email: 'rhonda32@gmail.com',
    password: hash,
    firstname: 'Rhonda',
    lastname: 'Rousey',
    user_type_id: 2,
    profile_image: 'profile4.jpg',
  },
  {
    username: 'LastOne',
    email: 'lastone@gmail.com',
    password: hash,
    firstname: 'Steve',
    lastname: 'Jobs',
    rating: 4,
    user_type_id: 2,
    profile_image: 'profile14.jpg',
  },

]
