// (c) Waveybits Inc. <2021>
// ALL RIGHTS RESERVED

const bcrypt = require('bcrypt');
const password = 'password';
const hash = bcrypt.hashSync(password, 10);

const categories = ['Website', 'Mobile App', 'Ecommerce', 'SAAS'];

module.exports = [
  {
    username: 'jeb',
    email: 'jeb352@gmail.com',
    password: hash,
    firstname: 'Jeb',
    lastname: 'Eichs',
    rating: 4,
    user_type_id: 1,
    bio: 'Ready to dedicate time to moving this idea forward.',
    visionary_categories: JSON.stringify([categories[0], categories[2], categories[3]]),
    profile_image: 'profile19.jpg',
    connections: JSON.stringify([1,7,12]),
    notifications: JSON.stringify([{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}]),
    tasks: JSON.stringify([{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: true, updates: true })
  },
  {
    username: 'jen38950',
    email: 'jen@gmail.com',
    password: hash,
    firstname: 'Jen',
    lastname: 'Smith',
    rating: 3,
    user_type_id: 1,
    bio: 'Ready to dedicate time to moving this idea forward.',
    visionary_categories: JSON.stringify([...categories]),
    profile_image: 'profile15.jpg',
    connections: JSON.stringify([2,8,13]),
    notifications: JSON.stringify([{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}]),
    tasks: JSON.stringify([{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: true, updates: true })
  },
  {
    username: 'beny89',
    email: 'beny89@gmail.com',
    password: hash,
    firstname: 'Ben',
    lastname: 'Antoitte',
    rating: 5,
    user_type_id: 1,
    bio: 'Ready to dedicate time to moving this idea forward.',
    visionary_categories: JSON.stringify([...categories]),
    profile_image: 'profile14.jpg',
    connections: JSON.stringify([4,9,14]),
    notifications: JSON.stringify([{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}]),
    tasks: JSON.stringify([{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: true, updates: true })
  },
  {
    username: 'appmaker',
    email: 'appmaker@gmail.com',
    password: hash,
    firstname: 'Ben',
    lastname: 'Hill',
    rating: 5,
    user_type_id: 1,
    bio: 'Ready to dedicate time to moving this idea forward.',
    visionary_categories: JSON.stringify([...categories]),
    profile_image: 'profile13.jpg',
    connections: null,
    notifications: JSON.stringify([{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}]),
    tasks: JSON.stringify([{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: true, updates: true })
  },
  {
    username: 'waveybits',
    email: 'waveybits@gmail.com',
    password: hash,
    firstname: 'Wavey',
    lastname: 'Boseman',
    rating: 4,
    user_type_id: 1,
    bio: 'Ready to dedicate time to moving this idea forward.',
    visionary_categories: JSON.stringify([categories[1]]),
    profile_image: 'profile12.jpg',
    connections: JSON.stringify([3,4,9,10,11,12,13,14,15]),
    notifications: JSON.stringify([{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}]),
    tasks: JSON.stringify([{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: true, updates: true })
  },
  {
    username: 'bossman',
    email: 'boss@devally.com',
    password: hash,
    firstname: 'Boss',
    lastname: 'Man',
    rating: 5,
    user_type_id: 1,
    bio: 'Ready to dedicate time to moving this idea forward.',
    visionary_categories: JSON.stringify([categories[0], categories[1], categories[2]]),
    profile_image: 'profile6.jpg',
    connections: JSON.stringify([7,11,4]),
    notifications: JSON.stringify([{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}]),
    tasks: JSON.stringify([{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: true, updates: true })
  },
  {
    username: 'cinyloo',
    email: 'cindyloo@gmail.com',
    password: hash,
    firstname: 'Cindy',
    lastname: 'Loo',
    rating: 5,
    user_type_id: 1,
    bio: 'Ready to dedicate time to moving this idea forward.',
    visionary_categories: JSON.stringify([...categories]),
    profile_image: 'profile10.jpg',
    connections: null,
    notifications: JSON.stringify([{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}]),
    tasks: JSON.stringify([{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: true, updates: true })
  },
  {
    username: 'androidDev',
    email: 'androiddev@gmail.com',
    password: hash,
    firstname: 'Clint',
    lastname: 'Summer',
    rating: 4,
    user_type_id: 1,
    bio: 'Work retail and have always wanted to create a mobile app. Looking for experienced team members.',
    visionary_categories: JSON.stringify([...categories]),
    profile_image: 'profile9.jpg',
    connections: null,
    notifications: JSON.stringify([{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}]),
    tasks: JSON.stringify([{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'yoohoo',
    email: 'yoohoo@gmail.com',
    password: hash,
    firstname: 'Yoo',
    lastname: 'Hoo',
    user_type_id: 1,
    bio: 'Work retail and have always wanted to create a mobile app. Looking for experienced team members.',
    visionary_categories: JSON.stringify([categories[2]]),
    profile_image: 'profile8.jpg',
    connections: null,
    notifications: JSON.stringify([{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}]),
    tasks: JSON.stringify([{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'gamer3521',
    email: 'gamer3521@gmail.com',
    password: hash,
    firstname: 'Jeff',
    lastname: 'Bloom',
    rating: 3,
    user_type_id: 1,
    bio: 'Work retail and have always wanted to create a mobile app. Looking for experienced team members.',
    visionary_categories: JSON.stringify([categories[0]]),
    profile_image: 'profile7.jpg',
    connections: null,
    notifications: JSON.stringify([{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}]),
    tasks: JSON.stringify([{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'iosDev',
    email: 'iosDev@gmail.com',
    password: hash,
    firstname: 'Anderson',
    lastname: 'Silva',
    user_type_id: 1,
    bio: 'Work retail and have always wanted to create a mobile app. Looking for experienced team members.',
    visionary_categories: JSON.stringify([categories[0], categories[1], categories[2]]),
    profile_image: 'profile3.jpg',
    connections: null,
    notifications: JSON.stringify([{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}]),
    tasks: JSON.stringify([{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'JoshB',
    email: 'JoshB@gmail.com',
    password: hash,
    firstname: 'Josh',
    lastname: 'Baker',
    rating: 4,
    user_type_id: 1,
    bio: 'Work retail and have always wanted to create a mobile app. Looking for experienced team members.',
    visionary_categories: JSON.stringify([...categories]),
    profile_image: 'profile2.jpg',
    connections: null,
    notifications: JSON.stringify([{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}]),
    tasks: JSON.stringify([{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'Gamebread',
    email: 'Gamebread@gmail.com',
    password: hash,
    firstname: 'Jorge',
    lastname: 'Masvidal',
    user_type_id: 1,
    bio: 'Not sure what to put here. Looking forward to starting my project.',
    visionary_categories: JSON.stringify([...categories]),
    profile_image: 'profile4.jpg',
    connections: null,
    notifications: JSON.stringify([{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}]),
    tasks: JSON.stringify([{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'bullet',
    email: 'bullet@gmail.com',
    password: hash,
    firstname: 'Valentina',
    lastname: 'Shevchenko',
    user_type_id: 1,
    bio: 'Not sure what to put here. Looking forward to starting my project.',
    visionary_categories: JSON.stringify([...categories]),
    profile_image: 'profile11.jpg',
    connections: null,
    notifications: JSON.stringify([{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}]),
    tasks: JSON.stringify([{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'The_Lioness',
    email: 'thelioness@gmail.com',
    password: hash,
    firstname: 'Amanda',
    lastname: 'Nunes',
    user_type_id: 1,
    bio: 'Not sure what to put here. Looking forward to starting my project.',
    visionary_categories: JSON.stringify([categories[1], categories[2]]),
    profile_image: 'profile5.jpg',
    connections: null,
    notifications: JSON.stringify([{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}]),
    tasks: JSON.stringify([{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'Vision',
    email: 'vision@gmail.com',
    password: hash,
    firstname: 'Vision',
    lastname: 'Marvel',
    user_type_id: 2,
    bio: 'Not sure what to put here. Looking forward to starting my project.',
    visionary_categories: JSON.stringify([categories[2]]),
    profile_image: 'profile2.jpg',
    connections: null,
    notifications: JSON.stringify([{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}]),
    tasks: JSON.stringify([{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'WandaM',
    email: 'wandam@gmail.com',
    password: hash,
    firstname: 'Wanda',
    lastname: 'Rhomboso',
    user_type_id: 2,
    bio: 'I am a visionary. Ambitious and self starter. Have multiple ideas for webapps.',
    visionary_categories: JSON.stringify([categories[3]]),
    profile_image: 'profile8.jpg',
    connections: null,
    notifications: JSON.stringify([{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}]),
    tasks: JSON.stringify([{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'IronMan',
    email: 'ironman@gmail.com',
    password: hash,
    firstname: 'Tony',
    lastname: 'Stark',
    user_type_id: 2,
    bio: 'I am a visionary. Ambitious and self starter. Have multiple ideas for webapps.',
    visionary_categories: JSON.stringify([...categories]),
    profile_image: 'profile10.jpg',
    connections: null,
    notifications: JSON.stringify([{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}]),
    tasks: JSON.stringify([{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'Captain America',
    email: 'captainamerica@gmail.com',
    password: hash,
    firstname: 'Cap',
    lastname: 'Rogers',
    user_type_id: 2,
    bio: 'I am a visionary. Ambitious and self starter. Have multiple ideas for webapps.',
    visionary_categories: JSON.stringify([...categories]),
    profile_image: 'profile10.jpg',
    connections: null,
    notifications: JSON.stringify([{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}]),
    tasks: JSON.stringify([{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'HulkDev',
    email: 'hulkdev@gmail.com',
    password: hash,
    firstname: 'Bruce',
    lastname: 'Banner',
    user_type_id: 2,
    bio: 'I am a visionary. Ambitious and self starter. Have multiple ideas for webapps.',
    visionary_categories: JSON.stringify([...categories]),
    profile_image: 'profile12.jpg',
    connections: null,
    notifications: JSON.stringify([{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}]),
    tasks: JSON.stringify([{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'BlackWidow',
    email: 'blackwidow@gmail.com',
    password: hash,
    firstname: 'Natasha',
    lastname: 'Romanov',
    user_type_id: 2,
    bio: 'I am a visionary. Ambitious and self starter. Have multiple ideas for webapps.',
    visionary_categories: JSON.stringify([categories[0], categories[3]]),
    profile_image: 'profile3.jpg',
    connections: null,
    notifications: JSON.stringify([{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}]),
    tasks: JSON.stringify([{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'Thor',
    email: 'thor@gmail.com',
    password: hash,
    firstname: 'Thor',
    lastname: 'Romanov',
    user_type_id: 2,
    bio: 'I am a visionary. Ambitious and self starter. Have multiple ideas for webapps.',
    visionary_categories: JSON.stringify([categories[2]]),
    profile_image: 'profile12.jpg',
    connections: null,
    notifications: JSON.stringify([{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}]),
    tasks: JSON.stringify([{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'Rhonda32',
    email: 'rhonda32@gmail.com',
    password: hash,
    firstname: 'Rhonda',
    lastname: 'Rousey',
    user_type_id: 2,
    bio: 'I am a visionary. Ambitious and self starter. Have multiple ideas for webapps.',
    visionary_categories: JSON.stringify([categories[1], categories[3]]),
    profile_image: 'profile4.jpg',
    connections: null,
    notifications: JSON.stringify([{ senderId: 4, projectId: null, message: 'Added you as a connection'},{ senderId: 12, projectId: 4, message: 'Recieved a project invitation'}]),
    tasks: JSON.stringify([{ projectId: 3, message: 'Find a front-end developer that has experience with VueJS' },{ projectId: 11, message: 'Create designs. Jen should have them completed by noon today' },{ projectId: 21, message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'}]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: false })
  },
  {
    username: 'LastOne',
    email: 'lastone@gmail.com',
    password: hash,
    firstname: 'Steve',
    lastname: 'Jobs',
    rating: 4,
    user_type_id: 2,
    bio: 'I am a visionary. Ambitious and self starter. Have multiple ideas for webapps.',
    visionary_categories: JSON.stringify([categories[0], categories[3]]),
    profile_image: 'profile14.jpg',
    connections: null,
    notifications: JSON.stringify([{
      senderId: 4,
      projectId: null,
      message: 'Added you as a connection'
    },
    {
      senderId: 12,
      projectId: 4,
      message: 'Recieved a project invitation'
    }]),
    tasks: JSON.stringify([{
      projectId: 3,
      message: 'Find a front-end developer that has experience with VueJS'
    },
    {
      projectId: 11,
      message: 'Create designs. Jen should have them completed by noon today'
    },
    {
      projectId: 21,
      message: 'Determine where to host application. Azure, Google Cloud and AWS are some viable options.'
    }]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },

]
