// (c) Waveybits Inc. <2021>
// ALL RIGHTS RESERVED

const bcrypt = require('bcrypt');
const password = 'password';
const hash = bcrypt.hashSync(password, 10);

const categories = ['Website', 'Mobile App', 'Ecommerce', 'SAAS'];
const notifications = [
  { senderId: 4, projectId: null, message: 'wants to add you as a connection', type: 'received' },
  { senderId: 12, projectId: 4, message: 'Project Invitation:', type: 'received' },
  { senderId: 4, projectId: null, message: 'is now one of your connections', type: 'accepted' },
  { senderId: 12, projectId: 4, message: 'has joined', type: 'accepted' }
]

module.exports = [
  {
    username: 'jeb',
    email: 'jeb352@gmail.com',
    password: hash,
    firstname: 'Jeb',
    lastname: 'Eichs',
    user_type_id: 1,
    ratings: JSON.stringify([ { rating: 4, user_rating_id: 12}, { rating: 4, user_rating_id: 5}, { rating: 5, user_rating_id: 2}]),
    bio: 'Ready to dedicate time to moving this idea forward.',
    visionary_categories: JSON.stringify([categories[0], categories[2], categories[3]]),
    profile_image: 'uploads/profile19.jpg',
    project_ids: JSON.stringify([1,3,5]),
    project_ids: JSON.stringify([1,3]),
    connections: JSON.stringify([1,7,12]),
    notifications: JSON.stringify([...notifications]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: true, updates: true })
  },
  {
    username: 'jen38950',
    email: 'jen@gmail.com',
    password: hash,
    firstname: 'Jen',
    lastname: 'Smith',
    user_type_id: 1,
    ratings: JSON.stringify([ { rating: 4, user_rating_id: 12}, { rating: 4, user_rating_id: 5}, { rating: 5, user_rating_id: 2}]),
    bio: 'Ready to dedicate time to moving this idea forward.',
    visionary_categories: JSON.stringify([...categories]),
    profile_image: 'uploads/profile15.jpg',
    project_ids: JSON.stringify([1]),
    connections: JSON.stringify([2,8,13]),
    notifications: JSON.stringify([...notifications]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: true, updates: true })
  },
  {
    username: 'beny89',
    email: 'beny89@gmail.com',
    password: hash,
    firstname: 'Ben',
    lastname: 'Antoitte',
    user_type_id: 1,
    ratings: JSON.stringify([ { rating: 5, user_rating_id: 12}, { rating: 4, user_rating_id: 5}, { rating: 5, user_rating_id: 2}]),
    bio: 'Ready to dedicate time to moving this idea forward.',
    visionary_categories: JSON.stringify([...categories]),
    profile_image: 'uploads/profile14.jpg',
    project_ids: JSON.stringify([2]),
    connections: JSON.stringify([4,9,14]),
    notifications: JSON.stringify([...notifications]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: true, updates: true })
  },
  {
    username: 'appmaker',
    email: 'appmaker@gmail.com',
    password: hash,
    firstname: 'Ben',
    lastname: 'Hill',
    user_type_id: 1,
    ratings: JSON.stringify([ { rating: 4, user_rating_id: 12}, { rating: 4, user_rating_id: 5}, { rating: 5, user_rating_id: 2}]),
    bio: 'Ready to dedicate time to moving this idea forward.',
    visionary_categories: JSON.stringify([...categories]),
    profile_image: 'uploads/profile13.jpg',
    project_ids: JSON.stringify([1]),
    connections: null,
    notifications: JSON.stringify([...notifications]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: true, updates: true })
  },
  {
    username: 'waveybits',
    email: 'waveybits@gmail.com',
    password: hash,
    firstname: 'Wavey',
    lastname: 'Boseman',
    user_type_id: 1,
    ratings: JSON.stringify([ { rating: 4, user_rating_id: 12}, { rating: 3, user_rating_id: 5}, { rating: 3, user_rating_id: 2}]),
    bio: 'Ready to dedicate time to moving this idea forward.',
    visionary_categories: JSON.stringify([categories[1]]),
    profile_image: 'uploads/profile12.jpg',
    project_ids: JSON.stringify([2, 3]),
    connections: JSON.stringify([3,4,9,10,11,12,13,14,15]),
    notifications: JSON.stringify([...notifications]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: true, updates: true })
  },
  {
    username: 'bossman',
    email: 'boss@devally.com',
    password: hash,
    firstname: 'Boss',
    lastname: 'Man',
    user_type_id: 1,
    ratings: JSON.stringify([ { rating: 5, user_rating_id: 12}, { rating: 4, user_rating_id: 5}, { rating: 5, user_rating_id: 2}]),
    bio: 'Ready to dedicate time to moving this idea forward.',
    visionary_categories: JSON.stringify([categories[0], categories[1], categories[2]]),
    profile_image: 'uploads/profile6.jpg',
    project_ids: JSON.stringify([1,4]),
    connections: JSON.stringify([7,11,4]),
    notifications: JSON.stringify([...notifications]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: true, updates: true })
  },
  {
    username: 'cinyloo',
    email: 'cindyloo@gmail.com',
    password: hash,
    firstname: 'Cindy',
    lastname: 'Loo',
    user_type_id: 1,
    ratings: JSON.stringify([ { rating: 4, user_rating_id: 12}, { rating: 4, user_rating_id: 5}, { rating: 5, user_rating_id: 2}]),
    bio: 'Ready to dedicate time to moving this idea forward.',
    visionary_categories: JSON.stringify([...categories]),
    profile_image: 'uploads/profile10.jpg',
    project_ids: JSON.stringify([2]),
    connections: null,
    notifications: JSON.stringify([...notifications]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: true, updates: true })
  },
  {
    username: 'androidDev',
    email: 'androiddev@gmail.com',
    password: hash,
    firstname: 'Clint',
    lastname: 'Summer',
    user_type_id: 1,
    ratings: JSON.stringify([ { rating: 4, user_rating_id: 12}, { rating: 4, user_rating_id: 5}, { rating: 5, user_rating_id: 2}]),
    bio: 'Work retail and have always wanted to create a mobile app. Looking for experienced team members.',
    visionary_categories: JSON.stringify([...categories]),
    profile_image: 'uploads/profile9.jpg',
    project_ids: JSON.stringify([3]),
    connections: null,
    notifications: JSON.stringify([...notifications]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'yoohoo',
    email: 'yoohoo@gmail.com',
    password: hash,
    firstname: 'Yoo',
    lastname: 'Hoo',
    user_type_id: 1,
    ratings: JSON.stringify([ { rating: 4, user_rating_id: 12}, { rating: 4, user_rating_id: 5}, { rating: 5, user_rating_id: 2}]),
    bio: 'Work retail and have always wanted to create a mobile app. Looking for experienced team members.',
    visionary_categories: JSON.stringify([categories[2]]),
    profile_image: 'uploads/profile8.jpg',
    project_ids: JSON.stringify([4]),
    connections: null,
    notifications: JSON.stringify([...notifications]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'gamer3521',
    email: 'gamer3521@gmail.com',
    password: hash,
    firstname: 'Jeff',
    lastname: 'Bloom',
    user_type_id: 1,
    ratings: JSON.stringify([ { rating: 4, user_rating_id: 12}, { rating: 4, user_rating_id: 5}, { rating: 5, user_rating_id: 2}]),
    bio: 'Work retail and have always wanted to create a mobile app. Looking for experienced team members.',
    visionary_categories: JSON.stringify([categories[0]]),
    profile_image: 'uploads/profile7.jpg',
    project_ids: JSON.stringify([4]),
    connections: null,
    notifications: JSON.stringify([...notifications]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'iosDev',
    email: 'iosDev@gmail.com',
    password: hash,
    firstname: 'Anderson',
    lastname: 'Silva',
    user_type_id: 1,
    ratings: JSON.stringify([ { rating: 5, user_rating_id: 12}, { rating: 5, user_rating_id: 5}, { rating: 2, user_rating_id: 2}]),
    bio: 'Work retail and have always wanted to create a mobile app. Looking for experienced team members.',
    visionary_categories: JSON.stringify([categories[0], categories[1], categories[2]]),
    profile_image: 'uploads/profile3.jpg',
    project_ids: JSON.stringify([3]),
    connections: null,
    notifications: JSON.stringify([...notifications]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'JoshB',
    email: 'JoshB@gmail.com',
    password: hash,
    firstname: 'Josh',
    lastname: 'Baker',
    user_type_id: 1,
    ratings: JSON.stringify([ { rating: 4, user_rating_id: 12}, { rating: 3, user_rating_id: 5}, { rating: 1, user_rating_id: 2}]),
    bio: 'Work retail and have always wanted to create a mobile app. Looking for experienced team members.',
    visionary_categories: JSON.stringify([...categories]),
    profile_image: 'uploads/profile2.jpg',
    project_ids: JSON.stringify([2]),
    connections: null,
    notifications: JSON.stringify([...notifications]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'Gamebread',
    email: 'Gamebread@gmail.com',
    password: hash,
    firstname: 'Jorge',
    lastname: 'Masvidal',
    user_type_id: 1,
    ratings: JSON.stringify([ { rating: 5, user_rating_id: 12}, { rating: 5, user_rating_id: 5}, { rating: 1, user_rating_id: 2}]),
    bio: 'Not sure what to put here. Looking forward to starting my project.',
    visionary_categories: JSON.stringify([...categories]),
    profile_image: 'uploads/profile4.jpg',
    project_ids: JSON.stringify([4,5]),
    connections: null,
    notifications: JSON.stringify([...notifications]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'bullet',
    email: 'bullet@gmail.com',
    password: hash,
    firstname: 'Valentina',
    lastname: 'Shevchenko',
    user_type_id: 1,
    ratings: JSON.stringify([ { rating: 5, user_rating_id: 12}, { rating: 3, user_rating_id: 5}, { rating: 1, user_rating_id: 2}]),
    bio: 'Not sure what to put here. Looking forward to starting my project.',
    visionary_categories: JSON.stringify([...categories]),
    profile_image: 'uploads/profile11.jpg',
    project_ids: null,
    connections: null,
    notifications: JSON.stringify([...notifications]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'The_Lioness',
    email: 'thelioness@gmail.com',
    password: hash,
    firstname: 'Amanda',
    lastname: 'Nunes',
    user_type_id: 1,
    ratings: JSON.stringify([ { rating: 5, user_rating_id: 12}, { rating: 3, user_rating_id: 5}, { rating: 2, user_rating_id: 2}]),
    bio: 'Not sure what to put here. Looking forward to starting my project.',
    visionary_categories: JSON.stringify([categories[1], categories[2]]),
    profile_image: 'uploads/profile5.jpg',
    project_ids: JSON.stringify([5]),
    connections: null,
    notifications: JSON.stringify([...notifications]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'Vision',
    email: 'vision@gmail.com',
    password: hash,
    firstname: 'Vision',
    lastname: 'Marvel',
    user_type_id: 2,
    ratings: JSON.stringify([ { rating: 2, user_rating_id: 12}, { rating: 3, user_rating_id: 5}, { rating: 2, user_rating_id: 2}]),
    bio: 'Not sure what to put here. Looking forward to starting my project.',
    visionary_categories: JSON.stringify([categories[2]]),
    profile_image: 'uploads/profile2.jpg',
    project_ids: JSON.stringify([5]),
    connections: null,
    notifications: JSON.stringify([...notifications]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'WandaM',
    email: 'wandam@gmail.com',
    password: hash,
    firstname: 'Wanda',
    lastname: 'Rhomboso',
    user_type_id: 2,
    ratings: JSON.stringify([ { rating: 5, user_rating_id: 12}, { rating: 3, user_rating_id: 5}, { rating: 4, user_rating_id: 2}]),
    bio: 'I am a visionary. Ambitious and self starter. Have multiple ideas for webapps.',
    visionary_categories: JSON.stringify([categories[3]]),
    profile_image: 'uploads/profile8.jpg',
    project_ids: null,
    connections: null,
    notifications: JSON.stringify([...notifications]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'IronMan',
    email: 'ironman@gmail.com',
    password: hash,
    firstname: 'Tony',
    lastname: 'Stark',
    user_type_id: 2,
    ratings: JSON.stringify([ { rating: 5, user_rating_id: 12}, { rating: 3, user_rating_id: 5}, { rating: 3, user_rating_id: 2}]),
    bio: 'I am a visionary. Ambitious and self starter. Have multiple ideas for webapps.',
    visionary_categories: JSON.stringify([...categories]),
    profile_image: 'uploads/profile10.jpg',
    project_ids: null,
    connections: null,
    notifications: JSON.stringify([...notifications]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'Captain America',
    email: 'captainamerica@gmail.com',
    password: hash,
    firstname: 'Cap',
    lastname: 'Rogers',
    user_type_id: 2,
    ratings: JSON.stringify([ { rating: 5, user_rating_id: 12}, { rating: 3, user_rating_id: 5}, { rating: 1, user_rating_id: 2}]),
    bio: 'I am a visionary. Ambitious and self starter. Have multiple ideas for webapps.',
    visionary_categories: JSON.stringify([...categories]),
    profile_image: 'uploads/profile10.jpg',
    project_ids: null,
    connections: null,
    notifications: JSON.stringify([...notifications]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'HulkDev',
    email: 'hulkdev@gmail.com',
    password: hash,
    firstname: 'Bruce',
    lastname: 'Banner',
    user_type_id: 2,
    ratings: JSON.stringify([ { rating: 2, user_rating_id: 12}, { rating: 3, user_rating_id: 5}, { rating: 1, user_rating_id: 2}]),
    bio: 'I am a visionary. Ambitious and self starter. Have multiple ideas for webapps.',
    visionary_categories: JSON.stringify([...categories]),
    profile_image: 'uploads/profile12.jpg',
    project_ids: null,
    connections: null,
    notifications: JSON.stringify([...notifications]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'BlackWidow',
    email: 'blackwidow@gmail.com',
    password: hash,
    firstname: 'Natasha',
    lastname: 'Romanov',
    user_type_id: 2,
    ratings: JSON.stringify([ { rating: 3, user_rating_id: 12}, { rating: 3, user_rating_id: 5}, { rating: 3, user_rating_id: 2}]),
    bio: 'I am a visionary. Ambitious and self starter. Have multiple ideas for webapps.',
    visionary_categories: JSON.stringify([categories[0], categories[3]]),
    profile_image: 'uploads/profile3.jpg',
    project_ids: null,
    connections: null,
    notifications: JSON.stringify([...notifications]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'Thor',
    email: 'thor@gmail.com',
    password: hash,
    firstname: 'Thor',
    lastname: 'Romanov',
    user_type_id: 2,
    ratings: JSON.stringify([ { rating: 5, user_rating_id: 12}, { rating: 5, user_rating_id: 5}, { rating: 4, user_rating_id: 2}]),
    bio: 'I am a visionary. Ambitious and self starter. Have multiple ideas for webapps.',
    visionary_categories: JSON.stringify([categories[2]]),
    profile_image: 'uploads/profile12.jpg',
    project_ids: null,
    connections: null,
    notifications: JSON.stringify([...notifications]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },
  {
    username: 'Rhonda32',
    email: 'rhonda32@gmail.com',
    password: hash,
    firstname: 'Rhonda',
    lastname: 'Rousey',
    user_type_id: 2,
    ratings: JSON.stringify([ { rating: 4, user_rating_id: 12}, { rating: 4, user_rating_id: 5}, { rating: 3, user_rating_id: 2}]),
    bio: 'I am a visionary. Ambitious and self starter. Have multiple ideas for webapps.',
    visionary_categories: JSON.stringify([categories[1], categories[3]]),
    profile_image: 'uploads/profile4.jpg',
    project_ids: null,
    connections: null,
    notifications: JSON.stringify([...notifications]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: false })
  },
  {
    username: 'LastOne',
    email: 'lastone@gmail.com',
    password: hash,
    firstname: 'Steve',
    lastname: 'Jobs',
    user_type_id: 2,
    ratings: JSON.stringify([ { rating: 5, user_rating_id: 12}, { rating: 3, user_rating_id: 5}, { rating: 1, user_rating_id: 2}]),
    bio: 'I am a visionary. Ambitious and self starter. Have multiple ideas for webapps.',
    visionary_categories: JSON.stringify([categories[0], categories[3]]),
    profile_image: 'uploads/profile14.jpg',
    project_ids: null,
    connections: null,
    notifications: JSON.stringify([...notifications]),
    notification_settings: JSON.stringify({ messages: true, added_connection: true, project_invitation: true }),
    subscription_settings: JSON.stringify({ featured_projects: true, weekly_news: false, updates: true })
  },

]
